from django.urls import path
from CPRapp import views
from django.contrib.auth import views as ad
urlpatterns = [
path('',views.home,name="hm"),
path('about/',views.about,name="about"),
path('contact/',views.contact,name="contact"),
path('achievements/',views.achievements,name="achievements"),
path('opinions/',views.opinions,name="cmopinions"),
path('reg/',views.register,name="reg"),
path('lg/',ad.LoginView.as_view(template_name='html/ulogin.html'),name="ulog"),
path('alg/',ad.LoginView.as_view(template_name='html/alogin.html'),name="alog"),
path('rst/',ad.PasswordResetView.as_view(template_name="html/resetpassword.html"),name="rt"),
path('rst_done/',ad.PasswordResetDoneView.as_view(template_name="html/resetpassworddone.html"),name="password_reset_done"),
path('rst_cf/<uidb64>/<token>/',ad.PasswordResetConfirmView.as_view(template_name="html/resetpasswordconfirm.html"),name="password_reset_confirm"),
path('rst_cmplt/',ad.PasswordResetCompleteView.as_view(template_name="html/resetpasswordcomplete.html"),name="password_reset_complete"),
path('dash/',views.dashboard,name="dash"),
path('logo/',ad.LogoutView.as_view(template_name='html/logout.html'),name="logo"),
path('pro/',views.profile,name="profile"),
path('updf/',views.updpf,name="upf"),
path('addpro/',views.addpro,name="addpro"),
path('addNewMember/',views.addmem,name="newmem"),
path('addwork/',views.addwork,name="addwork"),
path('workview/',views.workview,name="workview"),
path('addfm/',views.addfm,name="addfm"),
path('fmview/',views.fmview,name="fmview"),
path('pns/',views.pns,name="pns"),
path('pis/',views.pis,name="pis"),
path('ps/',views.ps,name="ps"),
path('allpro/',views.allpro,name="allpro"),
path('wrk/<int:id>/',views.workon,name="wrk"),
path('updatestatus/<int:id>/',views.Upstatus,name="updatestatus"),
path('vote/<int:id>/',views.vote,name="vote"),
path('vote1/<int:id>/',views.vote1,name="vote1"),
path('contview/',views.contview,name="contview"),
path('uview/',views.userview,name="userview"),
path('mview/',views.memview,name="memview"),
path('more/<int:id>/',views.more,name='more'),
path('del/<int:id>/',views.delete,name='dlt'),
path('memdel/<int:id>/',views.memdlt,name='memdlt'),
path('fmdel/<int:id>/',views.fmdlt,name='fmdlt'),
path('fmupdate/<int:id>/',views.fmupdate,name="fmupdate"),
path('cmupdate/<int:id>/',views.cmupdate,name="cmupdate"),
path('fmdel/<int:id>/',views.fmdlt,name='fmdlt'),
path('problemdel/<int:id>/',views.pdlt,name='pdlt'),
path('wupdate/<int:id>/',views.wupdate,name="wupdate"),
path('wdel/<int:id>/',views.wdlt,name='wdlt'),
path('givefeedback/<int:id>/',views.givefeedback,name='givefeedback'),


]