# Generated by Django 3.0 on 2021-04-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0004_auto_20210420_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
