# Generated by Django 3.0 on 2021-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0005_delete_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('aadharno', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('contactno', models.CharField(max_length=200)),
                ('password1', models.CharField(default=20, max_length=20)),
                ('password2', models.CharField(default=20, max_length=20)),
            ],
        ),
    ]
