# Generated by Django 3.0 on 2021-04-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0006_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
