# Generated by Django 3.0 on 2021-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0008_improfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=200)),
                ('pdesc', models.TextField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
