# Generated by Django 3.0 on 2021-04-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0009_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('ag', models.IntegerField(max_length=120)),
            ],
        ),
    ]
