# Generated by Django 3.0 on 2021-04-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0011_auto_20210424_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usrk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobno', models.IntegerField(default=7702630234)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CPRapp.Usrg')),
            ],
        ),
    ]
