# Generated by Django 3.0 on 2021-04-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0012_usrk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usrk',
            name='pid',
        ),
        migrations.DeleteModel(
            name='Usrg',
        ),
        migrations.DeleteModel(
            name='Usrk',
        ),
    ]
