# Generated by Django 3.0 on 2021-04-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0014_auto_20210424_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improfile',
            name='aadharno',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='improfile',
            name='contactno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
