# Generated by Django 3.0 on 2021-04-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0016_remove_improfile_impf'),
    ]

    operations = [
        migrations.AddField(
            model_name='improfile',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
