# Generated by Django 3.0 on 2021-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0019_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
