# Generated by Django 3.0 on 2021-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0020_problem_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pstatus',
            field=models.TextField(default='ns', max_length=200),
        ),
    ]
