# Generated by Django 3.0 on 2021-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0021_problem_pstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=200)),
                ('memail', models.EmailField(max_length=200)),
                ('mcno', models.CharField(default='', max_length=10)),
                ('mdoorno', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='pstatus',
            field=models.TextField(default='NotSolved', max_length=200),
        ),
    ]
