# Generated by Django 3.0 on 2021-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0025_auto_20210510_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pamount',
            field=models.IntegerField(default=0),
        ),
    ]
