# Generated by Django 3.0 on 2021-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0027_problem_paystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='estimatedtime',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='wassigned',
            field=models.CharField(default='', max_length=200),
        ),
    ]
