# Generated by Django 3.0 on 2021-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0028_auto_20210511_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='feedback',
            field=models.CharField(default='', max_length=200),
        ),
    ]
