# Generated by Django 3.0 on 2021-05-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0029_problem_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='useremail',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
