# Generated by Django 3.0 on 2021-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0030_problem_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='cfamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='xamount',
            field=models.IntegerField(default=0),
        ),
    ]
