# Generated by Django 3.0 on 2021-05-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0037_improfile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improfile',
            name='profilepic',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
    ]
