# Generated by Django 3.0 on 2021-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0002_auto_20210420_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='uname',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
