# Generated by Django 3.0 on 2021-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0010_usrg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrg',
            old_name='password',
            new_name='aadharno',
        ),
        migrations.RemoveField(
            model_name='usrg',
            name='ag',
        ),
        migrations.AddField(
            model_name='usrg',
            name='address',
            field=models.CharField(default=10, max_length=120),
        ),
        migrations.AddField(
            model_name='usrg',
            name='city',
            field=models.CharField(default=10, max_length=120),
        ),
        migrations.AddField(
            model_name='usrg',
            name='contactno',
            field=models.CharField(default=10, max_length=200),
        ),
        migrations.AddField(
            model_name='usrg',
            name='password1',
            field=models.CharField(default=10, max_length=120),
        ),
        migrations.AddField(
            model_name='usrg',
            name='password2',
            field=models.CharField(default=10, max_length=120),
        ),
        migrations.AlterField(
            model_name='usrg',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
