# Generated by Django 3.0 on 2021-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0017_improfile_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='postdate',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='postedby',
            field=models.CharField(default='', max_length=200),
        ),
    ]
