# Generated by Django 3.0 on 2021-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0018_auto_20210504_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=200)),
                ('wdesg', models.TextField()),
                ('contactno', models.CharField(default='', max_length=10)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
