# Generated by Django 3.0 on 2021-05-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0023_floormanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='improfile',
            old_name='place',
            new_name='doorno',
        ),
    ]
