# Generated by Django 3.0 on 2021-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0026_problem_pamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='paystatus',
            field=models.IntegerField(default=0),
        ),
    ]
