# Generated by Django 3.0 on 2021-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRapp', '0034_auto_20210512_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mimage',
            field=models.ImageField(default='', upload_to='Profiles/'),
        ),
    ]
